language: php

# Use container-based infrastructure
sudo: false

php:
  - 5.6
  - 7.0

before_script:
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - composer self-update
  - composer install --prefer-source

script: vendor/bin/codecept run unit --coverage --report --coverage-xml

after_success:
 - mkdir -p build/logs
 - cp tests/_output/coverage.xml build/logs/clover.xml
 - php vendor/bin/coveralls -v

